/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ARecord struct {
	Addresses []string `json:"addresses,omitempty"`
	Ttl       int32    `json:"ttl"`
	Name      string   `json:"name"`
}
