/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// OperatingSystem struct for OperatingSystem
type OperatingSystem struct {
	SshKey      bool `json:"sshKey,omitempty"`
	CloudInit   bool `json:"cloudInit,omitempty"`
	PostInstall bool `json:"postInstall,omitempty"`
}
