/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Permission struct for Permission
type Permission struct {
	Permissions []string `json:"permissions"`
	UserId      int32    `json:"userId"`
}
