/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// CancellationCreate struct for CancellationCreate
type CancellationCreate struct {
	DeviceId  int32  `json:"deviceId,omitempty"`
	Reason    string `json:"reason"`
	ServiceId int32  `json:"serviceId"`
}
