/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// DeviceInterface struct for DeviceInterface
type DeviceInterface struct {
	Status      int32  `json:"status,omitempty"`
	Name        string `json:"name,omitempty"`
	InterfaceId int32  `json:"interfaceId,omitempty"`
	Private     bool   `json:"private,omitempty"`
	SwitchName  string `json:"switchName,omitempty"`
	SwitchPort  string `json:"switchPort,omitempty"`
}
