/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// TicketPost struct for TicketPost
type TicketPost struct {
	Attachments            float32                `json:"attachments,omitempty"`
	ContactId              float32                `json:"contactId,omitempty"`
	Id                     float32                `json:"id,omitempty"`
	Subject                string                 `json:"subject,omitempty"`
	Hidden                 float32                `json:"hidden,omitempty"`
	ClientId               float32                `json:"clientId,omitempty"`
	TicketId               float32                `json:"ticketId,omitempty"`
	Body                   string                 `json:"body,omitempty"`
	UbersmithAttachedFiles []TicketAttach         `json:"ubersmith_attached_files,omitempty"`
	AdminId                float32                `json:"adminId,omitempty"`
	Date                   float32                `json:"date,omitempty"`
	FromAdmin              bool                   `json:"fromAdmin,omitempty"`
	From                   map[string]interface{} `json:"from,omitempty"`
}
