/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// DeviceIpmiInfo struct for DeviceIpmiInfo
type DeviceIpmiInfo struct {
	Info    IpmiInfo     `json:"info,omitempty"`
	Sensors []IpmiSensor `json:"sensors,omitempty"`
}
