/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VpsResetRootPassword struct {
	// The token used to reset the root password for the VPS instance.
	Token string `json:"token"`
}
