/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DeploymentCustomization struct {
	LocationCode string `json:"locationCode,omitempty"`
	Quantity int32 `json:"quantity,omitempty"`
	ProductId int32 `json:"productId"`
	Options []int32 `json:"options,omitempty"`
	AdditionalNotes []string `json:"additionalNotes,omitempty"`
	Hostnames []string `json:"hostnames"`
	// must be one of ['monthly', 'quarterly', 'semi-annually', 'annually', 'biennial', 'triennial']
	BillingPeriod string `json:"billingPeriod,omitempty"`
	OperatingSystem string `json:"operatingSystem"`
}
