/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// BareMetalDeviceBatchCreate struct for BareMetalDeviceBatchCreate
type BareMetalDeviceBatchCreate struct {
	Devices      []BareMetalDeviceCreate `json:"devices,omitempty"`
	OrderGroupId int32                   `json:"orderGroupId,omitempty"`
}
