/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Client struct {
	First    string      `json:"first,omitempty"`
	Id       float32     `json:"id,omitempty"`
	Email    string      `json:"email,omitempty"`
	City     string      `json:"city,omitempty"`
	IsClient bool        `json:"isClient,omitempty"`
	Company  string      `json:"company,omitempty"`
	Country  string      `json:"country,omitempty"`
	Zip      string      `json:"zip,omitempty"`
	FullName string      `json:"fullName,omitempty"`
	Last     string      `json:"last,omitempty"`
	Login    string      `json:"login,omitempty"`
	State    string      `json:"state,omitempty"`
	MetaData interface{} `json:"metaData,omitempty"`
}
