/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// WebhookUpdate struct for WebhookUpdate
type WebhookUpdate struct {
	Name    string                 `json:"name,omitempty"`
	Event   string                 `json:"event,omitempty"`
	Url     string                 `json:"url,omitempty"`
	Headers map[string]interface{} `json:"headers,omitempty"`
}
