/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PreviewEffectiveIgnition struct {
	Bonded           bool              `json:"bonded,omitempty"`
	Hostname         string            `json:"hostname,omitempty"`
	Password         string            `json:"password,omitempty"`
	PublicKeys       []string          `json:"publicKeys,omitempty"`
	PrimaryInterface *PrimaryInterface `json:"primaryInterface,omitempty"`
	Ignition         interface{}       `json:"ignition"`
}
