/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// VlanCreate struct for VlanCreate
type VlanCreate struct {
	Description string  `json:"description,omitempty"`
	DeviceIds   []int32 `json:"deviceIds,omitempty"`
}
