/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// DeploymentStart struct for DeploymentStart
type DeploymentStart struct {
	BillingInfo int32 `json:"billingInfo"`
}
