/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// SshKeyUpdate struct for SshKeyUpdate
type SshKeyUpdate struct {
	PublicKey string `json:"publicKey,omitempty"`
	Name      string `json:"name,omitempty"`
}
