/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// DeploymentCustomization struct for DeploymentCustomization
type DeploymentCustomization struct {
	// must be one of ['monthly', 'quarterly', 'semi-annually', 'annually', 'biennial', 'triennial']
	BillingPeriod   string   `json:"billingPeriod,omitempty"`
	Quantity        int32    `json:"quantity,omitempty"`
	Hostnames       []string `json:"hostnames"`
	AdditionalNotes []string `json:"additionalNotes,omitempty"`
	OperatingSystem string   `json:"operatingSystem"`
	LocationCode    string   `json:"locationCode,omitempty"`
	ProductId       int32    `json:"productId"`
	Options         []int32  `json:"options,omitempty"`
}
