/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// BareMetalDeviceCreate struct for BareMetalDeviceCreate
type BareMetalDeviceCreate struct {
	PublicSshKeyId int32    `json:"publicSshKeyId,omitempty"`
	OsName         string   `json:"osName"`
	Script         string   `json:"script,omitempty"`
	Period         string   `json:"period,omitempty"`
	ForceDeviceId  int32    `json:"forceDeviceId,omitempty"`
	VlanId         int32    `json:"vlanId,omitempty"`
	Hostname       string   `json:"hostname"`
	Tags           []string `json:"tags,omitempty"`
	LocationName   string   `json:"locationName"`
	ProductId      int32    `json:"productId"`
}
