/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// IpmiLoginData struct for IpmiLoginData
type IpmiLoginData struct {
	Password   string `json:"password,omitempty"`
	Username   string `json:"username,omitempty"`
	Drivertype string `json:"drivertype,omitempty"`
	Host       string `json:"host,omitempty"`
}
