/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BareMetalDeviceCreate struct {
	// A facility code. For example `NYC1`.
	LocationName string `json:"locationName"`
	VlanId       int32  `json:"vlanId,omitempty"`
	// For users with reserved devices. The unique ID of the target device to provision.
	ForceDeviceId int32 `json:"forceDeviceId,omitempty"`
	// The name of the Operating System to provision on this device. Must match name of an operating system product option.
	OsName string `json:"osName"`
	// A FQDN for the device. For example: `example.hivelocity.net`
	Hostname string `json:"hostname"`
	// Contents of iPXE script if not supplying URL
	CustomIPXEScriptContents string `json:"customIPXEScriptContents,omitempty"`
	// hourly|monthly|quarterly|semi-annually|annually|biennial|triennial
	Period string `json:"period,omitempty"`
	// User specified values.
	Tags []string `json:"tags,omitempty"`
	// The unique ID of an Ignition File for FlatcarOS provisions.
	IgnitionId int32 `json:"ignitionId,omitempty"`
	// The unique ID of the desired product to provision.
	ProductId      int32 `json:"productId"`
	PublicSshKeyId int32 `json:"publicSshKeyId,omitempty"`
	// A Cloud-Init script or a post-install script (Bash for Linux or Powershell for Windows).
	Script string `json:"script,omitempty"`
	// URL to download custom iPXE script if not supplying script in entirety
	CustomIPXEScriptURL string `json:"customIPXEScriptURL,omitempty"`
	// If true, ensures the provisioned device supports port bonding. If false, ensures no bonding support.
	BondingSupport bool `json:"bondingSupport,omitempty"`
}
