/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Location struct for Location
type Location struct {
	Location CityStateCountry `json:"location,omitempty"`
	Code     string           `json:"code,omitempty"`
	Core     bool             `json:"core,omitempty"`
	Edge     bool             `json:"edge,omitempty"`
}
