/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VpsNetworkCreate struct {
	// The name of the VPS Network.
	Name string `json:"name,omitempty"`
	// The VLAN ID of the VPS Network. This will make the network bridgeble to dedicated servers.
	VlanId int32 `json:"vlanId,omitempty"`
	// The facility code where the VPS Network should be created. For example: `TPA1`.
	FacilityCode string `json:"facilityCode"`
	// The unique client account ID.
	ClientId int32 `json:"clientId,omitempty"`
}
