/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// BareMetalDeviceBatch struct for BareMetalDeviceBatch
type BareMetalDeviceBatch struct {
	Devices      []BareMetalDevice `json:"devices,omitempty"`
	OrderGroupId int32             `json:"orderGroupId,omitempty"`
}
