/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// DeviceUpdate struct for DeviceUpdate
type DeviceUpdate struct {
	Name     string `json:"name,omitempty"`
	Hostname string `json:"hostname,omitempty"`
}
