/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// TicketPut struct for TicketPut
type TicketPut struct {
	Status string `json:"status,omitempty"`
}
