/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Password struct for Password
type Password struct {
	Password    string `json:"password"`
	NewPassword string `json:"newPassword"`
}
