/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// PasswordResponse struct for PasswordResponse
type PasswordResponse struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}
