/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// ElasticPoolCreate struct for ElasticPoolCreate
type ElasticPoolCreate struct {
	SubnetSize int32   `json:"subnetSize,omitempty"`
	DeviceIds  []int32 `json:"deviceIds,omitempty"`
}
