/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// ContactUpdate struct for ContactUpdate
type ContactUpdate struct {
	Phone       string `json:"phone,omitempty"`
	Active      int32  `json:"active,omitempty"`
	FullName    string `json:"fullName,omitempty"`
	Email       string `json:"email,omitempty"`
	Description string `json:"description,omitempty"`
}
