/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// PasswordRequest struct for PasswordRequest
type PasswordRequest struct {
	Email string `json:"email"`
}
