/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// OrderGroupCreate struct for OrderGroupCreate
type OrderGroupCreate struct {
	Name     string `json:"name"`
	SameRack bool   `json:"same_rack,omitempty"`
}
