/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// ProductMatch struct for ProductMatch
type ProductMatch struct {
	SpsOnly    bool                   `json:"spsOnly,omitempty"`
	LshwOutput map[string]interface{} `json:"lshwOutput,omitempty"`
}
