/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// ContactCreate struct for ContactCreate
type ContactCreate struct {
	Phone       string `json:"phone,omitempty"`
	Active      int32  `json:"active"`
	FullName    string `json:"fullName"`
	Email       string `json:"email"`
	Description string `json:"description,omitempty"`
	Password    string `json:"password,omitempty"`
}
