/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// SshKey struct for SshKey
type SshKey struct {
	Name      string `json:"name"`
	PublicKey string `json:"publicKey"`
}
