/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// MxRecordUpdate struct for MxRecordUpdate
type MxRecordUpdate struct {
	Name       string `json:"name,omitempty"`
	Exchange   string `json:"exchange"`
	Preference int32  `json:"preference"`
	Ttl        int32  `json:"ttl,omitempty"`
}
