/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ContactLoad struct {
	FullName string `json:"fullName"`
	IsClient bool `json:"isClient"`
	Login string `json:"login,omitempty"`
	Email string `json:"email"`
	Active int32 `json:"active"`
	Phone string `json:"phone,omitempty"`
	Password string `json:"password,omitempty"`
	Description string `json:"description"`
}
