/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// DeviceIpmiThresholds struct for DeviceIpmiThresholds
type DeviceIpmiThresholds struct {
	Thresholds map[string]interface{} `json:"thresholds"`
}
