/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VpsNetworkUpdate struct {
	// The name of the VPS Network.
	Name string `json:"name"`
}
