/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// DeviceIpmiWhitelistIp struct for DeviceIpmiWhitelistIp
type DeviceIpmiWhitelistIp struct {
	CustIp string `json:"custIp"`
}
