/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// AaaaRecordUpdate struct for AaaaRecordUpdate
type AaaaRecordUpdate struct {
	Name    string `json:"name,omitempty"`
	Address string `json:"address,omitempty"`
	Ttl     int32  `json:"ttl,omitempty"`
}
