/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ValidateCartCouponDump struct {
	// The coupon code to validate.
	CouponCode string                        `json:"couponCode"`
	Coupon     *ValidateCartCoupondumpCoupon `json:"coupon,omitempty"`
	// The unique client account ID.
	ClientId int32 `json:"clientId,omitempty"`
	// Error message if coupon is invalid.
	Error_ string `json:"error,omitempty"`
	// Whether the coupon is valid.
	IsValid bool `json:"isValid,omitempty"`
}
