/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// IpmiValidLogin struct for IpmiValidLogin
type IpmiValidLogin struct {
	Valid bool `json:"valid"`
}
