/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// OperatingSystem struct for OperatingSystem
type OperatingSystem struct {
	MonthlyPrice float32  `json:"monthlyPrice,omitempty"`
	Currency     string   `json:"currency,omitempty"`
	Expressions  []string `json:"expressions,omitempty"`
	Name         string   `json:"name,omitempty"`
	Id           int32    `json:"id,omitempty"`
	Tags         []string `json:"tags,omitempty"`
}
