/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// BandwidthImage struct for BandwidthImage
type BandwidthImage struct {
	GraphImage string `json:"graphImage,omitempty"`
	Interface  string `json:"interface,omitempty"`
	SwitchId   string `json:"switchId,omitempty"`
}
