/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Webhook struct for Webhook
type Webhook struct {
	WebhookId int32                  `json:"webhookId"`
	Name      string                 `json:"name"`
	Event     string                 `json:"event"`
	Url       string                 `json:"url"`
	Headers   map[string]interface{} `json:"headers,omitempty"`
}
