/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// ContactLoad struct for ContactLoad
type ContactLoad struct {
	IsClient    bool   `json:"isClient"`
	FullName    string `json:"fullName"`
	Description string `json:"description"`
	Active      int32  `json:"active"`
	Email       string `json:"email"`
	Password    string `json:"password,omitempty"`
	Login       string `json:"login,omitempty"`
	Phone       string `json:"phone,omitempty"`
}
