/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// TotalActiveCredit struct for TotalActiveCredit
type TotalActiveCredit struct {
	TotalActive float32 `json:"totalActive,omitempty"`
}
