/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// DetailedNullIp struct for DetailedNullIp
type DetailedNullIp struct {
	Comments string `json:"comments,omitempty"`
	Ip       string `json:"ip"`
}
