/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// InvoicePdf struct for InvoicePdf
type InvoicePdf struct {
	InvoiceId int32  `json:"invoiceId,omitempty"`
	PdfData   string `json:"pdfData,omitempty"`
}
