/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// InvoiceDetails struct for InvoiceDetails
type InvoiceDetails struct {
	AccountBalance  float32                      `json:"accountBalance,omitempty"`
	ClientAddress   string                       `json:"clientAddress,omitempty"`
	ClientName      string                       `json:"clientName,omitempty"`
	CompanyName     string                       `json:"companyName,omitempty"`
	InvoiceDate     time.Time                    `json:"invoiceDate,omitempty"`
	InvoiceDue      time.Time                    `json:"invoiceDue,omitempty"`
	InvoiceNumber   string                       `json:"invoiceNumber,omitempty"`
	ServiceItems    []InvoiceDetailsServiceItems `json:"serviceItems,omitempty"`
	TaxesValue      float32                      `json:"taxesValue,omitempty"`
	TotalDue        float32                      `json:"totalDue,omitempty"`
	PaymentHistory  []map[string]interface{}     `json:"paymentHistory,omitempty"`
	RefundHistory   []map[string]interface{}     `json:"refundHistory,omitempty"`
	TaxesList       []map[string]interface{}     `json:"taxesList,omitempty"`
	PriorBalance    float32                      `json:"priorBalance,omitempty"`
	PaymentsRefunds float32                      `json:"paymentsRefunds,omitempty"`
}
