/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// BillingInfoVerification struct for BillingInfoVerification
type BillingInfoVerification struct {
	VerificationAmount float32 `json:"verificationAmount,omitempty"`
	ProvisionOrderId   int32   `json:"provisionOrderId,omitempty"`
	Id                 int32   `json:"id"`
}
