/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Bandwidth struct for Bandwidth
type Bandwidth struct {
	Metadata      map[string]interface{} `json:"metadata,omitempty"`
	BandwidthData [][]float32            `json:"bandwidthData,omitempty"`
	Interface     string                 `json:"interface,omitempty"`
	SwitchId      string                 `json:"switchId,omitempty"`
}
