/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// TicketCreateReply struct for TicketCreateReply
type TicketCreateReply struct {
	Hidden      float32                  `json:"hidden,omitempty"`
	ReplyTo     string                   `json:"replyTo,omitempty"`
	Attachments []map[string]interface{} `json:"attachments,omitempty"`
	Encrypted   string                   `json:"encrypted,omitempty"`
	Date        float32                  `json:"date,omitempty"`
	Subject     string                   `json:"subject,omitempty"`
	Recipient   string                   `json:"recipient,omitempty"`
	ContactId   float32                  `json:"contactId,omitempty"`
	Headers     string                   `json:"headers,omitempty"`
	Type        float32                  `json:"type,omitempty"`
	Cc          string                   `json:"cc,omitempty"`
	Body        string                   `json:"body"`
}
