/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// PtrRecordUpdate struct for PtrRecordUpdate
type PtrRecordUpdate struct {
	Name string `json:"name"`
	Ttl  int32  `json:"ttl,omitempty"`
}
