/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VpsMetricsResponse struct {
	// The Metric Type requested.
	MetricType string `json:"metricType,omitempty"`
	// Actual Start Time for Chart Data.
	StartTime int32 `json:"startTime,omitempty"`
	// Base64 encoded Image Data.
	ImageData string `json:"imageData,omitempty"`
	// Actual End Time for Chart Data.
	EndTime int32 `json:"endTime,omitempty"`
}
