/*
 * Hivelocity API
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// MxRecordReturn struct for MxRecordReturn
type MxRecordReturn struct {
	Exchange   string `json:"exchange"`
	Preference int32  `json:"preference"`
	Id         int32  `json:"id"`
	Name       string `json:"name"`
	DomainId   int32  `json:"domainId"`
	Ttl        int32  `json:"ttl"`
	Type       string `json:"type"`
}
